import { Product } from "@shared/schema";

export const mockProducts: Product[] = [
  {
    id: 1,
    name: "Organic Carrots",
    category: "vegetables",
    description: "Fresh organic carrots perfect for restaurants and catering",
    imageUrl: "https://images.unsplash.com/photo-1620987278429-ab178d6eb547",
    pricePerKg: 2,
    minQuantity: 10,
    available: true,
  },
  {
    id: 2,
    name: "Premium Apples",
    category: "fruits",
    description: "Crisp and sweet apples sourced directly from local orchards",
    imageUrl: "https://images.unsplash.com/photo-1479064555552-3ef4979f8908",
    pricePerKg: 3,
    minQuantity: 20,
    available: true,
  },
  {
    id: 3,
    name: "Fresh Lettuce",
    category: "vegetables",
    description: "Hydroponically grown lettuce, perfect for salads and sandwiches",
    imageUrl: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1",
    pricePerKg: 4,
    minQuantity: 5,
    available: true,
  },
  {
    id: 4,
    name: "Bell Peppers Mix",
    category: "vegetables",
    description: "Colorful mix of red, yellow, and green bell peppers",
    imageUrl: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83",
    pricePerKg: 5,
    minQuantity: 10,
    available: true,
  },
  {
    id: 5,
    name: "Sweet Mangoes",
    category: "fruits",
    description: "Premium mangoes perfect for restaurants and juice bars",
    imageUrl: "https://images.unsplash.com/photo-1601493700631-2b16ec4b4716",
    pricePerKg: 6,
    minQuantity: 15,
    available: true,
  },
  {
    id: 6,
    name: "Fresh Oranges",
    category: "fruits",
    description: "Juicy citrus oranges ideal for fresh juice and culinary use",
    imageUrl: "https://images.unsplash.com/photo-1547514701-42782101795e",
    pricePerKg: 4,
    minQuantity: 20,
    available: true,
  },
  {
    id: 7,
    name: "Fresh Tomatoes",
    category: "vegetables",
    description: "Vine-ripened tomatoes perfect for salads and cooking",
    imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea",
    pricePerKg: 3,
    minQuantity: 10,
    available: true,
  },
  {
    id: 8,
    name: "Green Beans",
    category: "vegetables",
    description: "Crisp and tender green beans for wholesale buyers",
    imageUrl: "https://images.unsplash.com/photo-1567375698348-5d9d5ae99de0",
    pricePerKg: 4,
    minQuantity: 8,
    available: true,
  },
  {
    id: 9,
    name: "Fresh Berries Mix",
    category: "fruits",
    description: "Premium mix of strawberries, blueberries, and raspberries",
    imageUrl: "https://images.unsplash.com/photo-1563583991746-31aacf353cef",
    pricePerKg: 8,
    minQuantity: 5,
    available: true,
  },
];

export const partnerServices = [
  // Farmer Services
  {
    id: 1,
    title: "Bulk Seed & Equipment Supply",
    description: "Quality seeds and modern farming equipment for optimal yield",
    icon: "🌱",
    category: "farmer",
  },
  {
    id: 2,
    title: "Water & Irrigation Solutions",
    description: "Smart irrigation systems for efficient water management",
    icon: "💧",
    category: "farmer",
  },
  {
    id: 3,
    title: "Market Price & Demand Analytics",
    description: "Real-time market insights and demand forecasting",
    icon: "📈",
    category: "farmer",
  },
  {
    id: 4,
    title: "Weather & Climate Forecasting",
    description: "Accurate weather predictions for better crop planning",
    icon: "🌦",
    category: "farmer",
  },
  {
    id: 5,
    title: "Smart Crop Planning",
    description: "AI-powered crop planning for maximum yield",
    icon: "🌾",
    category: "farmer",
  },
  {
    id: 6,
    title: "Pest & Disease Management",
    description: "Integrated solutions for crop protection",
    icon: "🦟",
    category: "farmer",
  },
  {
    id: 7,
    title: "Government Schemes & Subsidies",
    description: "Stay updated with latest agricultural policies",
    icon: "📜",
    category: "farmer",
  },
  // Business Buyer Services
  {
    id: 8,
    title: "Expense & Profit Tracking",
    description: "Comprehensive financial management tools",
    icon: "💰",
    category: "business",
  },
  {
    id: 9,
    title: "Logistics Optimization",
    description: "Streamlined supply chain solutions",
    icon: "🏪",
    category: "business",
  },
  {
    id: 10,
    title: "Vendor Matching Services",
    description: "Connect with verified suppliers",
    icon: "🔍",
    category: "business",
  },
  {
    id: 11,
    title: "Wholesale Bulk Purchase",
    description: "Exclusive bulk buying options",
    icon: "🏢",
    category: "business",
  },
  {
    id: 12,
    title: "Real-Time Inventory & Pricing",
    description: "Live stock levels and dynamic pricing",
    icon: "📊",
    category: "business",
  },
];